# Generated by Django 3.0.3 on 2020-06-23 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('option_num', models.IntegerField(default=0)),
                ('voting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.Voting')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('voting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.Voting')),
            ],
        ),
    ]
